services:
  - type: web
    name: promo-screenshot-app
    env: python
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
      - key: PYTHONUNBUFFERED
        value: "1"
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
